### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by halfsail** [akay25/comet#56] opened 2020-11-16 05:17 UTC
Cannot continue sign up process on the birthday, phone number screen. After filling all the fields on the screen and clicking next button. I get a popup message saying "undefined".

**Comment by akay25** [comment] 2020-11-16 05:23
Yes, someone reported it last night as well.
Possible duplicate of #29 .

**Comment by akay25** [comment] 2021-01-05 19:48
Fixed the api and frontend

**Closed by akay25** 2021-01-05 19:48 UTC
Labels: UI, bug, duplicate
